### ISSUE TITLE
React Native Compatibility Gaps

### ISSUE THREAD

**Issue by hmallen99** [rebeckerspecialties/ir-engine#2]
```[tasklist]
### Tasks
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/5
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/3
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/7
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/8
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/9
```
