### ISSUE TITLE
Polyfill Browser APIs

### ISSUE THREAD

**Issue by hmallen99** [rebeckerspecialties/ir-engine#8]
```[tasklist]
### Tasks
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/10
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/11
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/12
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/14
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/13
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/15
- [ ] https://github.com/rebeckerspecialties/ir-engine/issues/17
```
